In [4]:
from tensorflow.keras.preprocessing.text import one_hot


In [13]:
##SETENCES
sent = [
    "Hello World less",
    "Good Morning go hapy",
    "Python Programming no",
    "Machine Learning" ,
    "Artificial Intelligence",
    "Data Science"
]


In [14]:
sent

['Hello World less',
 'Good Morning go hapy',
 'Python Programming no',
 'Machine Learning',
 'Artificial Intelligence',
 'Data Science']

In [15]:
##DEFINE THE VOCAB SIZE
voc_size=10000


In [16]:
##one hot encoder
onehot_repr = []
for words in sent:
    encoded_words = one_hot(words, voc_size)
    onehot_repr.append(encoded_words)

onehot_repr


[[5964, 1231, 7644],
 [9443, 7283, 6225, 9237],
 [6234, 429, 4547],
 [9226, 6533],
 [4078, 9506],
 [248, 9383]]

In [17]:
##word embedding represntation

from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential


In [21]:
import numpy as np# we making our sent for same length 

sent_length=8

enbedded_docs=pad_sequences(onehot_repr,padding='post',maxlen=sent_length)
print(enbedded_docs)



[[5964 1231 7644    0    0    0    0    0]
 [9443 7283 6225 9237    0    0    0    0]
 [6234  429 4547    0    0    0    0    0]
 [9226 6533    0    0    0    0    0    0]
 [4078 9506    0    0    0    0    0    0]
 [ 248 9383    0    0    0    0    0    0]]


In [22]:
#feature representation
dim=10


In [27]:
model=Sequential()
model.add(Embedding(voc_size,dim,input_length=sent_length))
model.compile('adam','mse')

In [28]:
model.summary()

Model: "sequential_2"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding_2 (Embedding)     (None, 8, 10)             100000    
                                                                 
Total params: 100000 (390.62 KB)
Trainable params: 100000 (390.62 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [29]:
model.predict(enbedded_docs)

1/1 [==============================] - 0s 56ms/step


array([[[-0.03528143,  0.00407265,  0.01971984,  0.0156878 ,
          0.03309411,  0.00368332, -0.00993689, -0.03807256,
         -0.03605872,  0.02863962],
        [-0.02600316, -0.02101119,  0.04034387, -0.04797291,
          0.01649744, -0.04914474, -0.0091732 , -0.0322051 ,
          0.01416372, -0.04172882],
        [ 0.01168818,  0.01620467, -0.00621986, -0.01705477,
         -0.02026852, -0.03035405, -0.04597261,  0.0336586 ,
         -0.04149518,  0.04857813],
        [ 0.02688416,  0.02477447,  0.03272042,  0.0475702 ,
         -0.02566689,  0.01709251,  0.03315021, -0.03224675,
         -0.0269788 , -0.02015947],
        [ 0.02688416,  0.02477447,  0.03272042,  0.0475702 ,
         -0.02566689,  0.01709251,  0.03315021, -0.03224675,
         -0.0269788 , -0.02015947],
        [ 0.02688416,  0.02477447,  0.03272042,  0.0475702 ,
         -0.02566689,  0.01709251,  0.03315021, -0.03224675,
         -0.0269788 , -0.02015947],
        [ 0.02688416,  0.02477447,  0.03272042,  0.0

In [31]:
enbedded_docs[0]#first sentence

array([5964, 1231, 7644,    0,    0,    0,    0,    0], dtype=int32)

In [32]:
model.predict(enbedded_docs[0])

1/1 [==============================] - 0s 29ms/step


array([[-0.03528143,  0.00407265,  0.01971984,  0.0156878 ,  0.03309411,
         0.00368332, -0.00993689, -0.03807256, -0.03605872,  0.02863962],
       [-0.02600316, -0.02101119,  0.04034387, -0.04797291,  0.01649744,
        -0.04914474, -0.0091732 , -0.0322051 ,  0.01416372, -0.04172882],
       [ 0.01168818,  0.01620467, -0.00621986, -0.01705477, -0.02026852,
        -0.03035405, -0.04597261,  0.0336586 , -0.04149518,  0.04857813],
       [ 0.02688416,  0.02477447,  0.03272042,  0.0475702 , -0.02566689,
         0.01709251,  0.03315021, -0.03224675, -0.0269788 , -0.02015947],
       [ 0.02688416,  0.02477447,  0.03272042,  0.0475702 , -0.02566689,
         0.01709251,  0.03315021, -0.03224675, -0.0269788 , -0.02015947],
       [ 0.02688416,  0.02477447,  0.03272042,  0.0475702 , -0.02566689,
         0.01709251,  0.03315021, -0.03224675, -0.0269788 , -0.02015947],
       [ 0.02688416,  0.02477447,  0.03272042,  0.0475702 , -0.02566689,
         0.01709251,  0.03315021, -0.03224675